export default {
  name:'testimonials',
  title:'Testimonial',
  type:'document',
  fields: [
    {
      name:'name',
      title:'Name',
      type:'string'
    },
    {
      name:'company',
      title:'Company',
      type:'string'
    },
    {
      name:'imageurl',
      title:'ImgURL',
      type:'image',
      options:{
        hotspot:true,
      }
    },
    {
      name:'projects',
      title:'Projects',
      type:'string'
    },
  ]
}